### PR TITLE
Wolfram Data Drop Code Snippet Fixed

### PR DESCRIPTION
**Pull request by kaz-baig**

### CODE REVIEW

**Comment by kurabi** [comment]
It seems like this PR was done in error as it modifies unrelated items to what the title indicates.

**Comment by simonatsafegraph** [comment]
@kurabi -- i think this just got out of sync with master, as we made conflicting changes. The intended change is probably the following:
```
 +  Alamofire.request(
 +    "https://datadrop.wolframcloud.com/api/v1.0/Add?bin=<YOUR BIN ID>",
 +		method: .post,
 +    parameters: location.locationFields,
 +		encoding: JSONEncoding.default
 +  )
 +  .responseJSON { response in
 +    debugPrint(response)
 +  }
 +}
```

@kaz-baig -- is that right?

**Comment by kaz-baig** [comment]
@simonatsafegraph That was indeed the intended change. My bad on not syncing with master before making the PR. Would you like me to make a new one?

**Comment by simonatsafegraph** [comment]
If you don't mind, that would be super helpful and keep things clean I think.

**Pull request closed without merging**
